# Generated by Django 5.2.3 on 2025-06-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='name',
            field=models.CharField(default='Custom', max_length=255),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['date'], name='sales_order_date_7840ba_idx'),
        ),
    ]
