# Generated by Django 5.2.3 on 2025-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_orderline_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
                ('stats_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['location'], name='sales_order_locatio_bf5b30_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['name'], name='sales_order_name_5ce52a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstats',
            index=models.Index(fields=['location'], name='sales_order_locatio_e5e0ef_idx'),
        ),
    ]
