# Generated by Django 5.2.3 on 2025-07-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_orderstats_orderline_sales_order_locatio_bf5b30_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrdersSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Custom', max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('total_sale', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'indexes': [models.Index(fields=['time'], name='sales_daily_time_6cd6e8_idx'), models.Index(fields=['location'], name='sales_daily_locatio_7ad051_idx'), models.Index(fields=['name'], name='sales_daily_name_df7ef7_idx')],
            },
        ),
    ]
