# Generated by Django 5.2.3 on 2025-07-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_dailyorderssnapshot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyOrdersSnapshot',
            new_name='DailyOrderSnapshot',
        ),
        migrations.RenameIndex(
            model_name='dailyordersnapshot',
            new_name='sales_daily_time_647a95_idx',
            old_name='sales_daily_time_6cd6e8_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyordersnapshot',
            new_name='sales_daily_locatio_e36043_idx',
            old_name='sales_daily_locatio_7ad051_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyordersnapshot',
            new_name='sales_daily_name_9c73cf_idx',
            old_name='sales_daily_name_df7ef7_idx',
        ),
    ]
