# Generated by Django 5.2.3 on 2025-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_dailyorderssnapshot_dailyordersnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyordersnapshot',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyordersnapshot',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
