# Generated by Django 5.2.3 on 2025-07-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_dailyordersnapshot_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyordersnapshot',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
