# Generated by Django 5.2.3 on 2025-07-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_dailyordersnapshot_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('delivery_date', models.DateField()),
                ('customer_name_first', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name_last', models.CharField(blank=True, max_length=255, null=True)),
                ('line_items', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['delivery_date'], name='sales_shopi_deliver_ab388d_idx')],
            },
        ),
    ]
