# Generated by Django 5.2.3 on 2025-07-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_shopifyorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
