# Generated by Django 5.2.3 on 2025-07-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_orderline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyordersnapshot',
            name='time',
            field=models.CharField(),
        ),
    ]
